#!/bin/bash

jar_file=build/jars/insteon-terminal.jar
path="${jar_file}:lib/*:lib/hub/*:lib/logger/*"

if [ ! -f $jar_file ];
then
   ant jar
fi

java -cp "${path}" us.pfrommer.insteon.cmd.Main "$@"

exit 0
